// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("Cube");

function _2dTransform(center) {
  var x = center[/* x */0];
  var y = center[/* y */1];
  var z = center[/* z */2];
  return /* :: */[
          /* tuple */[
            x - y | 0,
            (x + y | 0) + (z << 1) | 0
          ],
          /* :: */[
            /* tuple */[
              x - y | 0,
              ((x + y | 0) + (z << 1) | 0) + 1 | 0
            ],
            /* :: */[
              /* tuple */[
                x - y | 0,
                ((x + y | 0) + (z << 1) | 0) + 2 | 0
              ],
              /* :: */[
                /* tuple */[
                  (x - y | 0) + 1 | 0,
                  (x + y | 0) + (z << 1) | 0
                ],
                /* :: */[
                  /* tuple */[
                    (x - y | 0) + 1 | 0,
                    ((x + y | 0) + (z << 1) | 0) + 1 | 0
                  ],
                  /* :: */[
                    /* tuple */[
                      (x - y | 0) + 1 | 0,
                      ((x + y | 0) + (z << 1) | 0) + 2 | 0
                    ],
                    /* [] */0
                  ]
                ]
              ]
            ]
          ]
        ];
}

function xOrigin(side, triangle) {
  var edgeH = side * Math.sqrt(3.0) / 2.0;
  var x = triangle >= 3 ? edgeH : 0.0;
  return 350.0 - edgeH + x;
}

function make(_, _$1, _$2) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("div", {
                          className: "cube"
                        }, React.createElement("div", {
                              className: "triangle left-side"
                            }), React.createElement("div", {
                              className: "triangle right-side"
                            }), React.createElement("div", {
                              className: "triangle left-top"
                            }), React.createElement("div", {
                              className: "triangle right-front"
                            }), React.createElement("div", {
                              className: "triangle left-front"
                            }), React.createElement("div", {
                              className: "triangle right-top"
                            }));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

exports.component = component;
exports._2dTransform = _2dTransform;
exports.xOrigin = xOrigin;
exports.make = make;
/* component Not a pure module */
