// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Cube$ReactTemplate = require("./Cube.bs.js");

var component = ReasonReact.statelessComponent("Cube");

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return $$Array.of_list(List.map((function (c) {
                                return ReasonReact.element(/* None */0, /* None */0, Cube$ReactTemplate.make(c, /* array */[]));
                              }), /* :: */[
                              /* record */[
                                /* x */0,
                                /* y */0,
                                /* z */0
                              ],
                              /* :: */[
                                /* record */[
                                  /* x */1,
                                  /* y */0,
                                  /* z */0
                                ],
                                /* [] */0
                              ]
                            ]));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
